import { Product } from "@/types/store";

export const fallbackProducts: Product[] = [
  {
    id: "p1",
    name: "Hair Mask With Silk Protein",
    description: "Nourishing hair mask for dry and damaged hair.",
    price: 85,
    category: "Hair Care",
    skin_type: "All",
    image_url: "/images/hair mask 2.webp",
  },
  {
    id: "p2",
    name: "Hair Mask With Aloe Vera",
    description: "Hydrating formula that helps reduce frizz and breakage.",
    price: 85,
    category: "Hair Care",
    skin_type: "All",
    image_url: "/images/hair mask.jpg",
  },
  {
    id: "p3",
    name: "Hair Mask With Yogurt",
    description: "Protein-rich mask to improve shine and softness.",
    price: 85,
    category: "Hair Care",
    skin_type: "All",
    image_url: "/images/hair mask3.jpg",
  },
  {
    id: "p4",
    name: "Balsam For Hair",
    description: "Repair-focused balsam for smoother hair texture.",
    price: 160,
    category: "Hair Care",
    skin_type: "All",
    image_url: "/images/balsam.webp",
  },
  {
    id: "p5",
    name: "Shampoo And Balsam",
    description: "Complete duo for everyday cleansing and conditioning.",
    price: 530,
    category: "Hair Care",
    skin_type: "All",
    image_url: "/images/shampoo and balsam.webp",
  },
  {
    id: "p6",
    name: "Starville Acne Prone Facial Cleanser",
    description: "Targeted cleanser for acne-prone and oily skin.",
    price: 120,
    category: "Cleansers",
    skin_type: "Oily",
    image_url: "/images/cleaner.webp",
  },
  {
    id: "p7",
    name: "Starville Whitening Cleanser",
    description: "Brightening cleanser for dull and combination skin.",
    price: 190,
    category: "Cleansers",
    skin_type: "Combination",
    image_url: "/images/starville-whitening-cleanser.webp",
  },
  {
    id: "p8",
    name: "Soap And Glory Gloves",
    description: "Gentle exfoliation gloves for smoother body skin.",
    price: 240,
    category: "Body Care",
    skin_type: "Sensitive",
    image_url: "/images/soap-and-glory-gloves.webp",
  },
];
